import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/custom/Sidebar";
import Topbar from "@/components/custom/Topbar";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Task Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${plusJakartaSans.variable} antialiased w-screen h-screen overflow-hidden flex`}
      >
        <Sidebar />
        <div className="flex flex-col flex-1 h-screen">
          <Topbar />
          <div className="flex-1 overflow-y-auto bg-secondary-light p-2 flex">
            <div className="bg-white flex-1 rounded-lg flex flex-col h-full overflow-hidden space-y-2">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
